create table trash_stats (
  `id` int(11) NOT NULL,
  `agentid` int(11) NOT NULL,
  `companyid` int(11) NOT NULL,
  `raws` int(11) NOT NULL,
  `uniques` int(11) NOT NULL,
  `chargebacks` int(11) NOT NULL,
  `signups` int(11) DEFAULT NULL,
  `frauds` int(11) DEFAULT NULL,
  `sales_number` int(11) NOT NULL,
  `typeid` int(11) NOT NULL,
  `siteid` int(11) NOT NULL,
  `campaignid` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `trxtime` datetime NOT NULL,
  `transactionid` int(11) DEFAULT NULL
) ENGINE=MyISAM AUTO_INCREMENT=1548 DEFAULT CHARSET=ascii COLLATE=ascii_bin;
create table trash_companies (
  `id` int(11) unsigned NOT NULL,
  `officename` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `man1stname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `manlastname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `manemail` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `mancellphone` varchar(32) COLLATE ascii_bin DEFAULT NULL,
  `street` varchar(128) COLLATE ascii_bin NOT NULL COMMENT 'street name & number',
  `city` varchar(128) COLLATE ascii_bin NOT NULL,
  `state` varchar(128) COLLATE ascii_bin NOT NULL COMMENT 'state & zip',
  `country` varchar(2) COLLATE ascii_bin NOT NULL,
  `contactname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `payeename` varchar(64) COLLATE ascii_bin DEFAULT NULL COMMENT 'for the company',
  `payeeaddr1` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `payeeaddr2` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `payeecity` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `payeestate` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `payeezipcode` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `payeecountry` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `payeeemail` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `payouttype` tinyint(4) DEFAULT NULL COMMENT '0-pay by check, 1-pay by webstern uion, 2-pay by wire',
  `pps` decimal(8,2) NOT NULL DEFAULT '10.00',
  `paymentinfo` text COLLATE ascii_bin,
  `agentnotes` text COLLATE ascii_bin
) ENGINE=MyISAM DEFAULT CHARSET=ascii COLLATE=ascii_bin;
create table trash_agents (
  `id` int(11) unsigned NOT NULL,
  `name` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `paytoname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `keystring` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `companyid` int(11) NOT NULL,
  `ag1stname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `aglastname` varchar(64) COLLATE ascii_bin DEFAULT NULL,
  `email` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `street` varchar(256) COLLATE ascii_bin DEFAULT NULL COMMENT 'street name & number',
  `city` varchar(256) COLLATE ascii_bin DEFAULT NULL,
  `state` varchar(256) COLLATE ascii_bin DEFAULT NULL COMMENT 'state & zip',
  `country` varchar(2) COLLATE ascii_bin DEFAULT NULL,
  `im` varchar(128) COLLATE ascii_bin DEFAULT NULL,
  `cellphone` varchar(32) COLLATE ascii_bin DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=ascii COLLATE=ascii_bin;
